-- v3
-- Company logo

ALTER TABLE ACCOUNT DROP COMPANYLOGO;
ALTER TABLE ACCOUNT ADD COMPANYLOGO_TYPE VARCHAR(40) NULL;
ALTER TABLE ACCOUNT ADD COMPANYLOGO_CONTENT BLOB NULL;

-- @rollback

ALTER TABLE ACCOUNT DROP COMPANYLOGO_TYPE;
ALTER TABLE ACCOUNT DROP COMPANYLOGO_CONTENT;
ALTER TABLE ACCOUNT ADD COMPANYLOGO VARCHAR(200) NULL;
