-- v3
-- Company logo

ALTER TABLE ACCOUNT DROP COMPANYLOGO;
ALTER TABLE ACCOUNT ADD COMPANYLOGO_TYPE VARCHAR(40) NULL;
ALTER TABLE ACCOUNT ADD COMPANYLOGO_CONTENT BINARY(8000) NULL;

-- @rollback

ALTER TABLE ACCOUNT ADD COMPANYLOGO VARCHAR(200) NULL;
