-- v4
-- Contracts

CREATE TABLE CONTRACT (
  ID            INTEGER      NOT NULL AUTO_INCREMENT,
  TEACHERID     INTEGER      NOT NULL,
  SCHOOLID      INTEGER      NOT NULL,
  NAME          VARCHAR(80)  NOT NULL,
  HOURLYRATE    VARCHAR(20)  NULL,
  VATRATE       DECIMAL      NULL,
  CONSTRAINT CONTRACT_PK PRIMARY KEY (ID),
  CONSTRAINT CONTRACT_UQ UNIQUE (SCHOOLID, NAME),
  CONSTRAINT CONTRACT_FK_TEACHER FOREIGN KEY (TEACHERID) REFERENCES ACCOUNT (ID)
    ON DELETE CASCADE,
  CONSTRAINT CONTRACT_FK_SCHOOL FOREIGN KEY (TEACHERID, SCHOOLID) REFERENCES SCHOOL (TEACHERID, ID)
    ON DELETE CASCADE
);

ALTER TABLE STUDENT ADD CONTRACTID INTEGER NULL BEFORE NAME;

ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_FK_CONTRACT
FOREIGN KEY (TEACHERID, SCHOOLID, CONTRACTID)
REFERENCES CONTRACT(TEACHERID, SCHOOLID, ID);
