-- v1
-- Invoice management

CREATE TABLE INVOICE (
  ID           INTEGER     NOT NULL AUTO_INCREMENT,
  TEACHER      INTEGER     NOT NULL,
  STATUS       VARCHAR(16) NOT NULL,
  SCHOOL       INTEGER     NOT NULL,
  YEAR         INTEGER     NOT NULL,
  MONTH        INTEGER     NOT NULL,
  GENERATION   VARCHAR(32) NOT NULL,
  INVOICENB    INTEGER     NOT NULL,
  DOWNLOADED   BOOLEAN     NOT NULL,
  DOCUMENTTYPE VARCHAR(40) NOT NULL,
  DOCUMENT     BLOB        NULL,
  CONSTRAINT INVOICE_PK PRIMARY KEY (ID),
  CONSTRAINT INVOICE_UQ_INVOICENB UNIQUE (TEACHER, INVOICENB),
  CONSTRAINT INVOICE_FK_TEACHER FOREIGN KEY (TEACHER) REFERENCES ACCOUNT (ID)
    ON DELETE CASCADE,
  CONSTRAINT INVOICE_FK_SCHOOL FOREIGN KEY (TEACHER, SCHOOL) REFERENCES SCHOOL (TEACHERID, ID)
    ON DELETE CASCADE
);

ALTER TABLE ACCOUNT DROP INVOICELASTNB;
